/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 63
#define YY_END_OF_BUFFER 64
static yyconst short int yy_acclist[269] =
    {   0,
       64,   62,   63,    1,   62,   63,    1,   63,   62,   63,
       59,   62,   63,   49,   62,   63,   49,   62,   63,   51,
       62,   63,   52,   62,   63,   49,   62,   63,   50,   62,
       63,   49,   62,   63,   49,   62,   63,   49,   62,   63,
        4,   62,   63,    4,   62,   63,   49,   62,   63,   49,
       62,   63,   49,   62,   63,   49,   62,   63,   56,   62,
       63,   53,   62,   63,   53,   62,   63,   53,   62,   63,
       53,   62,   63,   53,   62,   63,   53,   62,   63,   53,
       62,   63,   53,   62,   63,   53,   62,   63,   53,   62,
       63,   14,   57,   61,   60,   61,   61,   41,   41,   41,

       41,   41,   41,   41,   41,   41,   41,   44,    2,   43,
       46,    4,   55,   45,   47,   42,   48,   53,   53,   53,
       53,   53,   15,   53,   20,   53,   53,   53,   53,   53,
       25,   53,   53,   53,   53,   58,   61,16438,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   13,16438,
       13,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,    2,    9,    3,    7,   16,   53,   17,
       53,   18,   53,   53,   21,   53,   22,   53,   23,   53,
       53,   26,   53,   53,   28,   53,   41,   41,   41,   41,
       35,   41,   36,   41,   37,   41,   41,   39,   41,   41,

       41,   40,   41,   12,    6,    9,    3,   19,   53,   24,
       53,   27,   53, 8246,   41,   41,   33,   41,   41,   41,
       41,   41,   41,   32,   41,   41,   38,   41,   41,   41,
        5,   11,    8,   31,   41,   34,   41,   41,   41,    5,
        8,   41,   41,   41,   41,   10,   41,   41,   10,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   29,   41,   41,   41,   41,   30,   41
    } ;

static yyconst short int yy_accept[211] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   11,   14,   17,
       20,   23,   26,   29,   32,   35,   38,   41,   44,   47,
       50,   53,   56,   59,   62,   65,   68,   71,   74,   77,
       80,   83,   86,   89,   92,   92,   93,   95,   97,   98,
       98,   98,   98,   98,   98,   99,  100,  101,  102,  103,
      104,  105,  106,  107,  108,  109,  110,  110,  110,  111,
      112,  112,  112,  113,  113,  113,  114,  115,  116,  117,
      118,  119,  120,  121,  122,  123,  125,  127,  128,  129,
      130,  131,  133,  134,  135,  136,  138,  139,  140,  141,
      142,  143,  144,  145,  146,  147,  148,  149,  151,  152,

      153,  154,  155,  156,  157,  158,  159,  160,  161,  162,
      163,  164,  165,  165,  165,  166,  166,  167,  168,  170,
      172,  174,  175,  177,  179,  181,  182,  184,  185,  187,
      187,  187,  188,  189,  190,  191,  193,  195,  197,  198,
      200,  201,  202,  204,  205,  206,  206,  206,  207,  207,
      208,  210,  212,  214,  215,  216,  217,  219,  220,  221,
      222,  223,  223,  223,  223,  224,  226,  227,  229,  230,
      231,  231,  232,  233,  233,  234,  236,  238,  239,  240,
      241,  241,  242,  243,  244,  244,  245,  246,  247,  248,
      249,  250,  251,  252,  253,  254,  255,  256,  257,  258,

      259,  260,  261,  262,  264,  265,  266,  267,  269,  269
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    5,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,    9,   22,
       23,   24,    5,   25,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       36,   43,   44,   45,   46,   47,   48,   49,   36,   36,
        9,    5,    9,    5,   26,    5,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   36,   43,   44,   45,   46,   47,   48,   49,
       36,   36,   25,    9,   25,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[50] =
    {   0,
        1,    1,    2,    3,    3,    3,    4,    5,    3,    6,
        3,    3,    3,    3,    3,    3,    7,    3,    8,    8,
        3,    3,    3,    3,    3,    9,    8,    8,    8,    8,
        8,    8,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10
    } ;

static yyconst short int yy_base[221] =
    {   0,
        0,    0,  551,  552,  552,  552,  544,   42,  552,   62,
      552,  552,  536,  552,  532,  110,  524,  109,  117,   30,
      523,  521,  521,  552,    0,   93,  505,   20,  501,   84,
      498,  509,  505,  497,  531,  552,   35,   37,    0,  526,
      158,  525,  524,  523,  207,  503,  496,   91,  111,  489,
      502,  501,  487,  499,  552,    0,  147,    0,  552,  552,
        0,   39,  250,  125,    0,  552,  552,  552,  552,  552,
        0,  481,  486,  493,  478,    0,    0,  491,  472,  474,
      480,    0,  476,  483,  470,  122,  256,  498,  251,  252,
      255,  256,  113,  258,  261,  107,  262,  271,  552,  497,

      268,  109,  254,  253,  269,  274,  280,  285,  122,  284,
      290,    0,  491,  289,  284,  282,  297,    0,    0,    0,
        0,  456,    0,    0,    0,  431,    0,  428,    0,  305,
      435,  289,  295,  301,  302,  445,  444,  443,  309,  440,
      311,  312,  439,  552,  417,    0,  323,  318,  315,  328,
        0,    0,    0,  552,  322,  323,  437,  324,  326,  331,
      340,  339,  439,  332,  345,  435,  346,  434,  350,  351,
      344,  351,  411,  434,  355,  429,  423,  355,  357,  367,
      362,  371,  363,  372,  379,  373,  375,  382,  362,  385,
      386,  399,  400,  403,  404,  406,  401,  405,  410,  407,

      409,  408,  411,  419,  412,  413,  414,  418,  552,  456,
      462,  465,  475,  485,  495,  417,  148,  502,  145,  508
    } ;

static yyconst short int yy_def[221] =
    {   0,
      209,    1,  209,  209,  209,  209,  210,  211,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  210,  209,  211,  211,  211,  213,
      209,   41,  213,  209,  209,   45,   45,   45,   45,   45,
       45,   45,   45,   45,  209,  214,  209,  215,  209,  209,
      216,  209,  209,  209,  217,  209,  209,  209,  209,  209,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  211,  209,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,  209,  209,   45,

       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,  214,  215,  218,  209,  209,  209,  217,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  209,
      209,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,  209,  209,  219,  218,  209,  209,  209,
      212,  212,  212,  209,   45,   45,   45,   45,   45,   45,
       45,  209,  220,  209,   45,   45,   45,   45,   45,   45,
      209,  209,  209,  220,  209,   45,   45,   45,   45,  209,
      209,  209,   45,   45,  209,   45,   45,  209,   45,   45,
      209,   45,   45,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   45,   45,   45,    0,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209
    } ;

static yyconst short int yy_nxt[602] =
    {   0,
        4,    5,    6,    5,    4,    7,    4,    8,    9,   10,
       11,   12,   13,    9,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   25,   25,   25,
       27,   25,   25,   25,   28,   25,   25,   25,   29,   30,
       31,   25,   32,   25,   33,   25,   25,   25,   34,   37,
       66,   76,   67,   86,   86,   38,   38,  115,  115,   77,
       38,   38,   40,   41,   41,   42,   43,   43,   43,   43,
       43,   44,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   45,   46,   45,
       45,   45,   45,   47,   45,   45,   45,   45,   45,   48,

       49,   45,   45,   50,   51,   45,   52,   53,   54,   45,
       45,   57,   57,   57,   79,   61,   87,  103,   87,   58,
       72,  104,   87,   61,   80,   62,   59,   63,   63,   81,
       73,   87,   74,   62,   63,   63,   63,  105,  116,   64,
       86,   86,   63,  117,  117,  106,  110,   64,   57,   57,
       57,  133,  163,  107,  140,  118,   58,   65,   40,   41,
       41,   41,   40,   40,   40,   40,   40,   87,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   88,   89,   88,   88,   88,   88,   90,
       88,   88,   88,   88,   88,   91,   92,   88,   88,   93,

       94,   88,   95,   96,   97,   88,   88,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   98,   40,   40,   40,
       40,   40,   40,   40,   40,  100,  100,   40,   40,   40,
       40,   40,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,   61,  130,  130,  130,
       87,   87,   87,   87,   87,   87,   62,   87,   63,   63,
       87,   87,  130,  130,  130,   63,  131,   87,   87,  101,
       64,  103,  105,   87,  108,  104,  102,  109,  111,   87,
      106,  131,  135,   87,   87,  145,  132,  134,   87,   87,

      117,  117,  148,  148,   87,  146,  130,  130,  130,  148,
       87,   87,  141,  137,  149,  150,  150,  136,   87,  155,
       87,   87,  150,  138,  139,  131,  142,  143,  164,  145,
      164,   87,   87,   87,  158,   87,  148,  148,  156,  146,
       87,  159,  161,  148,  160,  157,  150,  150,  149,   87,
      175,  175,  171,  150,   87,   87,  168,  172,  172,   87,
       87,  169,  172,  172,   87,  165,   87,  166,  167,  180,
      180,   87,   87,  182,  182,  185,  180,  185,  178,  177,
      182,   87,   87,  170,   87,  180,  180,  192,  176,  182,
      182,  183,  180,  186,   87,  179,  182,  188,  188,  184,

      191,  191,  189,  190,  191,  191,  187,  191,   87,   87,
       87,  191,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,  114,  194,  199,   87,   87,  193,
      195,  196,   87,  197,  198,  200,  201,  203,   87,  205,
      173,  181,  206,   87,   87,  173,   87,  162,   87,   87,
      202,  204,   87,   87,   87,  154,  207,  208,   35,   35,
       35,   35,   35,   35,   35,   35,   39,  153,  152,   39,
       39,   39,   71,   71,   71,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,  112,  151,  112,  112,  112,
      112,  112,  112,  112,  112,  113,  113,  113,  113,  113,

      144,  113,  113,  113,  113,  147,   87,   87,  147,  147,
      147,  174,  129,  128,  127,  174,  174,  126,  125,  124,
      123,  122,  121,  120,  119,  111,  110,  109,  108,  107,
      102,  101,   99,   98,   98,   87,   36,   85,   84,   83,
       82,   78,   75,   70,   69,   68,   60,   56,   55,   36,
      209,    3,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,

      209
    } ;

static yyconst short int yy_chk[602] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    8,
       20,   28,   20,   37,   37,   38,   38,   62,   62,   28,
        8,    8,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,

       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   16,   16,   16,   30,   18,   96,   48,  102,   16,
       26,   48,   93,   19,   30,   18,   16,   18,   18,   30,
       26,  109,   26,   19,   18,   19,   19,   49,   64,   18,
       86,   86,   19,   64,   64,   49,   96,   19,   57,   57,
       57,  102,  219,   93,  109,  217,   57,   18,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,

       41,   41,   41,   41,   41,   41,   41,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   63,   87,   87,   87,
       89,   90,  104,  103,   91,   92,   63,   94,   63,   63,
       95,   97,   98,   98,   98,   63,   87,  101,  105,   89,
       63,   91,   92,  106,   94,   91,   90,   95,   97,  107,
       92,   98,  104,  110,  108,  114,  101,  103,  132,  111,

      116,  116,  115,  115,  133,  114,  130,  130,  130,  115,
      134,  135,  110,  106,  115,  117,  117,  105,  139,  132,
      141,  142,  117,  107,  108,  130,  110,  111,  149,  147,
      149,  155,  156,  158,  135,  159,  148,  148,  133,  147,
      160,  139,  142,  148,  141,  134,  150,  150,  148,  161,
      164,  164,  162,  150,  165,  167,  159,  162,  162,  169,
      170,  160,  171,  171,  178,  155,  179,  156,  158,  172,
      172,  189,  183,  175,  175,  181,  172,  181,  169,  167,
      175,  184,  186,  161,  187,  180,  180,  189,  165,  182,
      182,  178,  180,  183,  190,  170,  182,  185,  185,  179,

      188,  188,  186,  187,  191,  191,  184,  188,  192,  193,
      197,  191,  194,  195,  198,  196,  200,  202,  201,  199,
      203,  205,  206,  207,  216,  192,  197,  208,  204,  190,
      193,  194,  177,  195,  196,  198,  199,  201,  176,  203,
      174,  173,  205,  168,  166,  163,  157,  145,  143,  140,
      200,  202,  138,  137,  136,  131,  206,  207,  210,  210,
      210,  210,  210,  210,  210,  210,  211,  128,  126,  211,
      211,  211,  212,  212,  212,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  214,  122,  214,  214,  214,
      214,  214,  214,  214,  214,  215,  215,  215,  215,  215,

      113,  215,  215,  215,  215,  218,  100,   88,  218,  218,
      218,  220,   85,   84,   83,  220,  220,   81,   80,   79,
       78,   75,   74,   73,   72,   54,   53,   52,   51,   50,
       47,   46,   44,   43,   42,   40,   35,   34,   33,   32,
       31,   29,   27,   23,   22,   21,   17,   15,   13,    7,
        3,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,

      209
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "ada-lex.l"
#define INITIAL 0
/* FLEX lexer for Ada expressions, for GDB.
   Copyright (C) 1994, 1997
   Free Software Foundation, Inc.

This file is part of GDB.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  */
/*----------------------------------------------------------------------*/
/* The converted version of this file is to be included in ada-exp.y, */
/* the Ada parser for gdb.  The function yylex obtains characters from */
/* the global pointer lexptr.  It returns a syntactic category for */
/* each successive token and places a semantic value into yylval */
/* (ada-lval), defined by the parser.   */
/* Run flex with (at least) the -i option (case-insensitive), and the -I */
/* option (interactive---no unnecessary lookahead).  */
#line 47 "ada-lex.l"
#define NUMERAL_WIDTH 256

/* Temporary staging for numeric literals. */
static char numbuf[NUMERAL_WIDTH]; 

static void canonicalizeNumeral PARAMS ((char* s1, const char*));
static int processInt PARAMS ((const char*, const char*, const char*));
static int processReal PARAMS ((const char*));
static int processId PARAMS ((const char*, int));
static int digitval PARAMS ((char));

#undef YY_DECL
#define YY_DECL static int yylex PARAMS (( void )) 

#undef YY_INPUT
#define YY_INPUT(BUF, RESULT, MAX_SIZE) \
    if ( *lexptr == '\000' ) \
      (RESULT) = YY_NULL; \
    else \
      { \
        *(BUF) = *lexptr; \
        (RESULT) = 1; \
	lexptr += 1; \
      }

static char *tempbuf = NULL;
static int tempbufsize = 0;

static void
resize_tempbuf PARAMS ((unsigned int));


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 80 "ada-lex.l"



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 210 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 552 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 82 "ada-lex.l"
{ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 84 "ada-lex.l"
{ yyterminate(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 86 "ada-lex.l"
{ 
		   canonicalizeNumeral (numbuf, yytext); 
		   return processInt (NULL, numbuf, strrchr(numbuf, 'e')+1);
		 }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 91 "ada-lex.l"
{ 
		   canonicalizeNumeral (numbuf, yytext); 
		   return processInt (NULL, numbuf, NULL);
		 }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 96 "ada-lex.l"
{
		   canonicalizeNumeral (numbuf, yytext);
    		   return processInt (numbuf,
				      strchr (numbuf, '#') + 1, 
				      strrchr(numbuf, '#') + 1);
		 }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 103 "ada-lex.l"
{
		   canonicalizeNumeral (numbuf, yytext);
    		   return processInt (numbuf, strchr (numbuf, '#') + 1, NULL);
		 }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 108 "ada-lex.l"
{
		  canonicalizeNumeral (numbuf, yytext+2);
		  return processInt ("16#", numbuf, NULL);
		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 114 "ada-lex.l"
{
		   canonicalizeNumeral (numbuf, yytext); 
		   return processReal (numbuf);
		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 119 "ada-lex.l"
{
		   canonicalizeNumeral (numbuf, yytext); 
		   return processReal (numbuf);
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 124 "ada-lex.l"
{
                   error ("Based real literals not implemented yet.");
		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 128 "ada-lex.l"
{
                   error ("Based real literals not implemented yet.");
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 132 "ada-lex.l"
{ 
		  char* name = strchr(yytext, '\'') + 1;
                  processId(name, yyleng-(name-yytext)-1);
		  yylval.sval = yylval.ssym.stoken;
		  return DOT_LITERAL_NAME;
		}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 140 "ada-lex.l"
{
		   yylval.typed_val.type = builtin_type_ada_char;
		   yylval.typed_val.val = yytext[1];
		   return INT;
		}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 146 "ada-lex.l"
{
		   resize_tempbuf (yyleng-1);
		   strncpy(tempbuf, yytext+1, yyleng-2);
		   tempbuf[yyleng-2] = '\000';
		   yylval.sval.ptr = tempbuf;
		   yylval.sval.length = yyleng-2;
		   return STRING;
		}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 155 "ada-lex.l"
{ 
		  while (*lexptr != 'i' && *lexptr != 'I') 
		    lexptr -= 1; 
		  yyrestart(NULL); 
		  return 0;
		}
	YY_BREAK
/* ADA KEYWORDS */
case 16:
YY_RULE_SETUP
#line 164 "ada-lex.l"
{ return ABS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 165 "ada-lex.l"
{ return ALL; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 166 "ada-lex.l"
{ return _AND_; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 167 "ada-lex.l"
{ return ELSE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 168 "ada-lex.l"
{ return IN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 169 "ada-lex.l"
{ return MOD; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 170 "ada-lex.l"
{ return NEW; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 171 "ada-lex.l"
{ return NOT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 172 "ada-lex.l"
{ return NULL_PTR; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 173 "ada-lex.l"
{ return OR; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 174 "ada-lex.l"
{ return REM; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 175 "ada-lex.l"
{ return THEN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 176 "ada-lex.l"
{ return XOR; }
	YY_BREAK
/* ATTRIBUTES */
case 29:
#line 181 "ada-lex.l"
case 30:
#line 182 "ada-lex.l"
case 31:
YY_RULE_SETUP
#line 182 "ada-lex.l"
{ return TICK_ACCESS; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 183 "ada-lex.l"
{ return TICK_FIRST; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 184 "ada-lex.l"
{ return TICK_LAST; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 185 "ada-lex.l"
{ return TICK_LENGTH; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 186 "ada-lex.l"
{ return TICK_MAX; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 187 "ada-lex.l"
{ return TICK_MIN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 188 "ada-lex.l"
{ return TICK_POS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 189 "ada-lex.l"
{ return TICK_RANGE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 190 "ada-lex.l"
{ return TICK_TAG; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 191 "ada-lex.l"
{ return TICK_VAL; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 192 "ada-lex.l"
{ error ("unrecognized attribute: `%s'", yytext+1); } 
	YY_BREAK
/* PUNCTUATION */
case 42:
YY_RULE_SETUP
#line 196 "ada-lex.l"
{ return ARROW; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 197 "ada-lex.l"
{ return DOTDOT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 198 "ada-lex.l"
{ return STARSTAR; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 199 "ada-lex.l"
{ return ASSIGN; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 200 "ada-lex.l"
{ return NOTEQUAL; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 201 "ada-lex.l"
{ return LEQ; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 202 "ada-lex.l"
{ return GEQ; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 204 "ada-lex.l"
{ return yytext[0]; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 206 "ada-lex.l"
{ if (paren_depth == 0 && comma_terminates)
		    {
		      lexptr -= 2;
		      yyrestart(NULL);
		      return 0;
		    }
		  else 
		    return ',';
		}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 216 "ada-lex.l"
{ paren_depth += 1; return '('; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 217 "ada-lex.l"
{ if (paren_depth == 0) 
		    {
		      lexptr -= 2;
		      yyrestart(NULL);
		      return 0;
		    }
		  else 
 		    {
		      paren_depth -= 1; 
		      return ')';
		    }
		}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 230 "ada-lex.l"
{ return processId(yytext, yyleng); }
	YY_BREAK
/* GDB EXPRESSION CONSTRUCTS  */
case 54:
YY_RULE_SETUP
#line 234 "ada-lex.l"
{ 
                  return processId(yytext+1, yyleng-2);
		}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 238 "ada-lex.l"
{ return COLONCOLON; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 239 "ada-lex.l"
{ return yytext[0]; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 241 "ada-lex.l"
{ yylval.lval = -1; return LAST; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 242 "ada-lex.l"
{ yylval.lval = -atoi(yytext+2); return LAST; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 243 "ada-lex.l"
{ yylval.lval = 0; return LAST; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 244 "ada-lex.l"
{ yylval.lval = atoi(yytext+1); return LAST; }
	YY_BREAK
/* REGISTERS AND GDB CONVENIENCE VARIABLES */
case 61:
YY_RULE_SETUP
#line 249 "ada-lex.l"
{
    		  int c;
		  for (c = 0; c < NUM_REGS; c++)
		    if (strcmp (yytext + 1, reg_names[c]) == 0)
		      {
			yylval.lval = c;
			return REGNAME;
		      }
		  for (c = 0; c < num_std_regs; c++)
		    if (strcmp (yytext+1, std_regs[c].name) == 0)
		      {	
			yylval.lval = std_regs[c].regnum;
			return REGNAME;
		      }
		  yylval.sval.ptr = yytext;
		  yylval.sval.length = yyleng;
		  yylval.ivar = 
		    lookup_internalvar (copy_name (yylval.sval) + 1);
		  return INTERNAL_VARIABLE;
		}
	YY_BREAK
/* CATCH-ALL ERROR CASE */
case 62:
YY_RULE_SETUP
#line 272 "ada-lex.l"
{ error ("Invalid character '%s' in expression.", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 273 "ada-lex.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 210 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 210 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 209);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 273 "ada-lex.l"


/* Make sure that tempbuf points at an array at least N characters long. */

static void
resize_tempbuf (n)
     unsigned int n;
{
  if (tempbufsize < n)
    {
      tempbufsize = (n+63) & ~63;
      tempbuf = (char*) xrealloc (tempbuf, tempbufsize);
    }
}
 

/* Convert hex digit c into the corresponding int 0-15. */

static int
digitval(c)
     char c;
{
  if (isdigit(c))
    return c - '0';
  else
    return tolower(c) - 'a' + 10;
}


/* Copy S2 to S1, removing all underscores, and downcasing all letters. */

static void
canonicalizeNumeral (s1,s2)
     char* s1;
     const char* s2;
{
  for (; *s2 != '\000'; s2 += 1) 
    {
      if (*s2 != '_')
	{
	  *s1 = tolower(*s2);
	  s1 += 1;
	}
    }
  s1[0] = '\000';
}

#define HIGH_BYTE_POSN ((sizeof (unsigned LONGEST) - 1) * 8)

/* True (non-zero) iff DIGIT is a valid digit in radix BASE, 
   where 2 <= BASE <= 16.  */

static int
is_digit_in_base (digit, base)
     unsigned char digit;
     int base;
{
  if (!isxdigit (digit))
    return 0;
  if (base <= 10)
    return (isdigit (digit) && digit < base + '0');
  else 
    return (isdigit (digit) || tolower (digit) < base - 10 + 'a');
}

static int
digit_to_int (c)
     unsigned char c;
{
  if (isdigit (c))
    return c - '0';
  else
    return tolower (c) - 'a' + 10;
}

/* As for strtoul, but for unsigned LONGEST results. */
unsigned LONGEST
strtoulst (num, trailer, base)
     const char *num;
     const char **trailer;
     int base;
{
  unsigned long high_part;
  unsigned LONGEST result;
  int i;
  unsigned char lim;

  if (base < 2 || base > 16)
    {
      errno = EINVAL;
      return 0;
    }
  lim = base - 1 + '0';

  result = high_part = 0;
  for (i = 0; is_digit_in_base (num[i], base); i += 1)
    {
      result = result*base + digit_to_int (num[i]);
      high_part = high_part*base + result >> HIGH_BYTE_POSN;
      result &= (1 << HIGH_BYTE_POSN) - 1;
      if (high_part > 0xff) 
	{
	  errno = ERANGE;
	  result = high_part = 0;
	  break;
	}
    }

  if (trailer != NULL)
    *trailer = &num[i];

  return result + (high_part << HIGH_BYTE_POSN);
}



/* Interprets the prefix of NUM that consists of digits of the given BASE
   as an integer of that BASE, with the string EXP as an exponent.
   Puts value in *semval, and returns INT, if the string is valid.  Causes
   an error if the number.   BASE, if NULL, defaults to "10", and EXP to "1".
   The EXP does not contain a leading 'e' or 'E'. */

static int
processInt (base0, num0, exp0)
     const char* num0;
     const char* base0;
     const char* exp0;
{
  LONGEST result;
  long exp;
  int base;

  char* trailer;

  if (base0 == NULL)
    base = 10;
  else
    {	
      base = strtol (base0, (char**) NULL, 10);
      if (base < 2 || base > 16)
	error ("Invalid base: %d.", base);
    }

  if (exp0 == NULL)
    exp = 0;
  else
    exp = strtol(exp0, (char**) NULL, 10);

  errno = 0;
  result = strtoulst (num0, &trailer, base);
  if (errno == ERANGE)
	error ("Integer literal out of range");
  if (isxdigit(*trailer))
    error ("Invalid digit `%c' in based literal", *trailer);

  while (exp > 0) 
    {
      if (result > (ULONG_MAX / base))
	error ("Integer literal out of range");
      result *= base;
      exp -= 1;
    }
  
  yylval.typed_val.val = result;
  yylval.typed_val.type = builtin_type_ada_int;

  return INT;
}

static int
processReal (num0)
     const char* num0;
{
  if (sizeof (DOUBLEST) <= sizeof (float))
    {
      sscanf (num0, "%g", &yylval.typed_val_float.dval);
      yylval.typed_val_float.type = builtin_type_ada_float;
    }
  else if (sizeof (DOUBLEST) <= sizeof (double))
    {
      sscanf (num0, "%lg", &yylval.typed_val_float.dval);
      yylval.typed_val_float.type = builtin_type_ada_double;
    }
  else
    {
#ifdef PRINTF_HAS_LONG_DOUBLE
      sscanf (num0, "%Lg", &yylval.typed_val_float.dval);
#else
      /* Scan it into a double, then convert and assign it to the 
	 long double.  This at least wins with values representable 
	 in the range of doubles. */
      double temp;
      sscanf (num0, "%lg", &temp);
      yylval.typed_val_float.dval = temp;
#endif
      yylval.typed_val_float.type = builtin_type_ada_long_double;
    }
  return FLOAT;
}

static int
processId (name0, len)
     const char *name0;
     int len;
{
  struct symbol** syms;
  struct block** blocks;
  int nsyms;
  char* name = savestring (name0, len);
  char* lc_name = save_downcase_string (name0, len);
  int i, k;

  add_name_string_cleanup (name);

  nsyms = ada_lookup_symbol_list (name, expression_context_block,
				  VAR_NAMESPACE, &syms, &blocks);


  /* Call lookup_symtab, not lookup_partial_symtab, in case there are
     no psymtabs (coff, xcoff, or some future change to blow away the
     psymtabs once symbols are read).  */
  if ((nsyms == 1 && SYMBOL_CLASS (syms[0]) == LOC_BLOCK)
      || lookup_symtab (name) != NULL
      || lookup_symtab (lc_name) != NULL)
    {
      if (nsyms == 1)
	yylval.ssym.sym = syms[0];
      else
	yylval.ssym.sym = NULL;
      yylval.ssym.is_a_field_of_this = 0;
      yylval.ssym.stoken.ptr = name;
      yylval.ssym.stoken.length = len;
      return BLOCKNAME;
    }

  /* Check for a type definition. */

  /* Look for a symbol that doesn't denote void.  This is (I think) a */
  /* temporary kludge to get around problems in GNAT output. */
  k = -1;
  for (i = 0; i < nsyms; i += 1)
    {
      if (SYMBOL_CLASS (syms[i]) == LOC_TYPEDEF && 
	  TYPE_CODE (SYMBOL_TYPE (syms[i])) != TYPE_CODE_VOID)
	{
	  yylval.tsym.type = SYMBOL_TYPE (syms[i]);
	  yylval.tsym.stoken.ptr = name;
	  yylval.tsym.stoken.length = len;
	  return TYPENAME;
	}
      else if (SYMBOL_CLASS (syms[i]) == LOC_TYPEDEF)
	k = i;
    }
  if (k != -1)
    error ("`%s' matches only void type name(s)", name);

  yylval.tsym.type = lookup_primitive_typename (lc_name);
  if (yylval.tsym.type != NULL)
    {
      yylval.tsym.stoken.ptr = name;
      yylval.tsym.stoken.length = len;
      return TYPENAME;
    }
  
  /* Any other kind of symbol */
  yylval.ssym.sym = NULL;
  yylval.tsym.stoken.ptr = name;
  yylval.tsym.stoken.length = len;
  yylval.ssym.is_a_field_of_this = 0;
  return NAME;
}

int
yywrap()
{
  return 1;
}
